sudo: false
language: node_js
node_js:
- '10'

cache:
  directories:
  - $HOME/.pkg

install:
- yarn

script:
- npm run ci

before_deploy:
  - npm run pkg

deploy:
  provider: releases
  api_key:
    secure: dSDFAwoeOUepD2e+z3j3rnpWeaRXfNb4lolYbG9ekI2BOW4TIWNsBPLUJmwc+QD2AKs+HEqKcme5vizFTZXnJnto8Vt4RJLXP1HlKOt9ML9SO/IIw+oJbeqHNnawXCouC3d47t3YRmLXzzzUKCx++kLoYxE6cprceUjFJzR0p0y0Qx6L5Lzeg0rCImumcyVRPPRgq6+OFNgwRl9xFZIRcoXOPv+5CUt3xzmGU/KhSs+pAPICFcRkdlQz9oeYkytOIIakzSJj8vBOUWPlQN7qt1uhMUAdtBUepL006zAY6+F49gDMCRuNfrWLqGV02BwfAuPrMCtMm+0QzyTUGLWj4zx0uRMN1hHUG8YxHTU/H8JxovAk1b92Q3O9N5GU6MrUw6pAja2MvvrqZDtL9A7yJeXHVJnPeMdtYpedDmv5ykM5uDdPXrPX91OcOTlXDvY1w9iuS4zMhkQ6LPsUMIa2sxF/e06bO23jjKmI9I9Xq7vf1xIGrsxzhLbMYc8Ntc4wmWuDi4yh28avdjPHR2c65MFit1fHs1YuyDIWygNfB1mPogp8oWydzyfs4RfMnPZjObsnCpVW8TX/rdsERra7kjzdRpLDCV6bzkSPazmLKwFP3aacB/cz7YLVh+wYwPyGODS6h3mBoO+yMWvIOSEUUcUO+Nat2C1iWIIg7CcnoIo=
  file_glob: true
  skip_cleanup: true
  file: "./build/*"
  on:
    repo: Rokid/yoda-platform-tools
    tags: true
